// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​d​d​ ​n​e​w
	 */
	addNew: string
	/**
	 * A​i​r​p​o​r​t
	 */
	airport: string
	/**
	 * A​l​t​i​t​u​d​e
	 */
	altitude: string
	/**
	 * C​a​l​l​ ​S​i​g​n
	 */
	callSign: string
	cardinalDirections: {
		/**
		 * N
		 */
		N: string
		/**
		 * E
		 */
		E: string
		/**
		 * S
		 */
		S: string
		/**
		 * W
		 */
		W: string
	}
	/**
	 * c​l​o​s​e​ ​n​o​t​e​s
	 */
	closeNotes: string
	/**
	 * C​o​u​r​s​e
	 */
	course: string
	/**
	 * C​r​u​i​s​e​ ​s​p​e​e​d
	 */
	cruiseSpeed: string
	/**
	 * D​a​t​e
	 */
	date: string
	/**
	 * D​i​s​t​.
	 */
	distance_abbr: string
	/**
	 * D​i​s​t​a​n​c​e
	 */
	distance: string
	/**
	 * F​l​i​g​h​t​ ​P​l​a​n
	 */
	flightPlan: string
	/**
	 * F​r​e​q​.
	 */
	frequencies_abbr: string
	/**
	 * F​r​e​q​u​e​n​c​i​e​s
	 */
	frequencies: string
	/**
	 * F​u​e​l
	 */
	fuel: string
	/**
	 * F​u​e​l​ ​C​a​p​a​c​i​t​y
	 */
	fuelCapacity: string
	/**
	 * F​u​e​l​ ​F​l​o​w
	 */
	fuelFlow: string
	/**
	 * F​u​e​l​ ​R​e​s​e​r​v​e
	 */
	fuelReserve: string
	/**
	 * I​n​c​l​u​d​e​ ​f​r​e​q​u​e​n​c​i​e​s
	 */
	includeFrequencies: string
	/**
	 * l​e​a​v​e​ ​a​ ​c​o​m​m​e​n​t
	 */
	leaveFeedback: string
	/**
	 * M​a​p
	 */
	map: string
	/**
	 * n​m
	 */
	nauticalMiles_unit: string
	/**
	 * N​o​t​e​s​…
	 */
	notes_placeholder: string
	/**
	 * o​p​e​n​ ​n​o​t​e​s
	 */
	openNotes: string
	/**
	 * P​l​a​n​e
	 */
	plane: string
	/**
	 * R​u​n​w​a​y​s
	 */
	runways: string
	/**
	 * S​e​a​r​c​h​ ​P​O​I​s
	 */
	searchPOI: string
	/**
	 * T​i​t​l​e
	 */
	title: string
	/**
	 * T​o​t​a​l​s
	 */
	totals: string
	/**
	 * W​i​n​d​ ​d​i​r​e​c​t​i​o​n​ ​a​n​d​ ​s​p​e​e​d​ ​[​d​i​r​/​s​p​e​e​d​]
	 */
	wind_help: string
	/**
	 * W​i​n​d
	 */
	wind: string
}

export type TranslationFunctions = {
	/**
	 * Add new
	 */
	addNew: () => LocalizedString
	/**
	 * Airport
	 */
	airport: () => LocalizedString
	/**
	 * Altitude
	 */
	altitude: () => LocalizedString
	/**
	 * Call Sign
	 */
	callSign: () => LocalizedString
	cardinalDirections: {
		/**
		 * N
		 */
		N: () => LocalizedString
		/**
		 * E
		 */
		E: () => LocalizedString
		/**
		 * S
		 */
		S: () => LocalizedString
		/**
		 * W
		 */
		W: () => LocalizedString
	}
	/**
	 * close notes
	 */
	closeNotes: () => LocalizedString
	/**
	 * Course
	 */
	course: () => LocalizedString
	/**
	 * Cruise speed
	 */
	cruiseSpeed: () => LocalizedString
	/**
	 * Date
	 */
	date: () => LocalizedString
	/**
	 * Dist.
	 */
	distance_abbr: () => LocalizedString
	/**
	 * Distance
	 */
	distance: () => LocalizedString
	/**
	 * Flight Plan
	 */
	flightPlan: () => LocalizedString
	/**
	 * Freq.
	 */
	frequencies_abbr: () => LocalizedString
	/**
	 * Frequencies
	 */
	frequencies: () => LocalizedString
	/**
	 * Fuel
	 */
	fuel: () => LocalizedString
	/**
	 * Fuel Capacity
	 */
	fuelCapacity: () => LocalizedString
	/**
	 * Fuel Flow
	 */
	fuelFlow: () => LocalizedString
	/**
	 * Fuel Reserve
	 */
	fuelReserve: () => LocalizedString
	/**
	 * Include frequencies
	 */
	includeFrequencies: () => LocalizedString
	/**
	 * leave a comment
	 */
	leaveFeedback: () => LocalizedString
	/**
	 * Map
	 */
	map: () => LocalizedString
	/**
	 * nm
	 */
	nauticalMiles_unit: () => LocalizedString
	/**
	 * Notes…
	 */
	notes_placeholder: () => LocalizedString
	/**
	 * open notes
	 */
	openNotes: () => LocalizedString
	/**
	 * Plane
	 */
	plane: () => LocalizedString
	/**
	 * Runways
	 */
	runways: () => LocalizedString
	/**
	 * Search POIs
	 */
	searchPOI: () => LocalizedString
	/**
	 * Title
	 */
	title: () => LocalizedString
	/**
	 * Totals
	 */
	totals: () => LocalizedString
	/**
	 * Wind direction and speed [dir/speed]
	 */
	wind_help: () => LocalizedString
	/**
	 * Wind
	 */
	wind: () => LocalizedString
}

export type Formatters = {}
