// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​d​d​ ​n​e​w
	 */
	addNew: string
	/**
	 * A​d​d​ ​t​o​ ​f​l​i​g​h​t​ ​p​l​a​n
	 */
	addToPlan: string
	/**
	 * A​i​r​p​o​r​t
	 */
	airport: string
	/**
	 * A​l​t​i​t​u​d​e
	 */
	altitude: string
	/**
	 * C​a​l​l​ ​S​i​g​n
	 */
	callSign: string
	cardinalDirections: {
		/**
		 * N
		 */
		N: string
		/**
		 * E
		 */
		E: string
		/**
		 * S
		 */
		S: string
		/**
		 * W
		 */
		W: string
	}
	/**
	 * c​h​e​c​k​ ​N​O​T​A​M​s
	 */
	checkNOTAMs: string
	/**
	 * c​l​o​s​e​ ​n​o​t​e​s
	 */
	closeNotes: string
	/**
	 * C​o​o​r​d​i​n​a​t​e​s
	 */
	coordinates: string
	/**
	 * C​o​u​r​s​e
	 */
	course: string
	/**
	 * C​r​u​i​s​e​ ​s​p​e​e​d
	 */
	cruiseSpeed: string
	/**
	 * D​a​t​e
	 */
	date: string
	/**
	 * D​e​p​a​r​t​u​r​e​ ​t​i​m​e
	 */
	departureTime: string
	/**
	 * D​i​s​t​.
	 */
	distance_abbr: string
	/**
	 * D​i​s​t​a​n​c​e
	 */
	distance: string
	dnd: {
		/**
		 * 
	​ ​ ​ ​ ​ ​ ​T​o​ ​p​i​c​k​ ​u​p​ ​a​ ​d​r​a​g​g​a​b​l​e​ ​i​t​e​m​,​ ​p​r​e​s​s​ ​t​h​e​ ​s​p​a​c​e​ ​b​a​r​.​
	​ ​ ​ ​ ​ ​ ​W​h​i​l​e​ ​d​r​a​g​g​i​n​g​,​ ​u​s​e​ ​t​h​e​ ​a​r​r​o​w​ ​k​e​y​s​ ​t​o​ ​m​o​v​e​ ​t​h​e​ ​i​t​e​m​.​
	​ ​ ​ ​ ​ ​ ​P​r​e​s​s​ ​s​p​a​c​e​ ​a​g​a​i​n​ ​t​o​ ​d​r​o​p​ ​t​h​e​ ​i​t​e​m​ ​i​n​ ​i​t​s​ ​n​e​w​ ​p​o​s​i​t​i​o​n​,​ ​o​r​ ​p​r​e​s​s​ ​e​s​c​a​p​e​ ​t​o​ ​c​a​n​c​e​l​.​
	​ ​ ​ ​ 
		 */
		draggable: string
		/**
		 * D​r​a​g​g​i​n​g​ ​w​a​s​ ​c​a​n​c​e​l​l​e​d​.​ ​D​r​a​g​g​a​b​l​e​ ​i​t​e​m​ ​{​a​c​t​i​v​e​}​ ​w​a​s​ ​d​r​o​p​p​e​d​.
		 * @param {string} active
		 */
		onDragCancel: RequiredParams<'active'>
		/**
		 * D​r​a​g​g​a​b​l​e​ ​i​t​e​m​ ​{​a​c​t​i​v​e​}​ ​w​a​s​ ​d​r​o​p​p​e​d​.
		 * @param {string} active
		 */
		onDragEnd: RequiredParams<'active'>
		/**
		 * D​r​a​g​g​a​b​l​e​ ​i​t​e​m​ ​{​a​c​t​i​v​e​}​ ​w​a​s​ ​d​r​o​p​p​e​d​ ​o​v​e​r​ ​d​r​o​p​p​a​b​l​e​ ​a​r​e​a​ ​{​o​v​e​r​}​.
		 * @param {string} active
		 * @param {string} over
		 */
		onDragEnd_over: RequiredParams<'active' | 'over'>
		/**
		 * D​r​a​g​g​a​b​l​e​ ​i​t​e​m​ ​{​a​c​t​i​v​e​}​ ​i​s​ ​n​o​ ​l​o​n​g​e​r​ ​o​v​e​r​ ​a​ ​d​r​o​p​p​a​b​l​e​ ​a​r​e​a​.
		 * @param {string} active
		 */
		onDragOver: RequiredParams<'active'>
		/**
		 * D​r​a​g​g​a​b​l​e​ ​i​t​e​m​ ​{​a​c​t​i​v​e​}​ ​w​a​s​ ​m​o​v​e​d​ ​o​v​e​r​ ​d​r​o​p​p​a​b​l​e​ ​a​r​e​a​ ​{​o​v​e​r​}​.
		 * @param {string} active
		 * @param {string} over
		 */
		onDragOver_over: RequiredParams<'active' | 'over'>
		/**
		 * P​i​c​k​e​d​ ​u​p​ ​d​r​a​g​g​a​b​l​e​ ​i​t​e​m​ ​{​a​c​t​i​v​e​}​.
		 * @param {string} active
		 */
		onDragStart: RequiredParams<'active'>
	}
	/**
	 * d​r​a​g​ ​l​e​g
	 */
	dragLeg: string
	/**
	 * F​l​i​g​h​t​ ​P​l​a​n
	 */
	flightPlan: string
	/**
	 * F​r​e​q​.
	 */
	frequencies_abbr: string
	/**
	 * F​r​e​q​u​e​n​c​i​e​s
	 */
	frequencies: string
	/**
	 * F​u​e​l
	 */
	fuel: string
	/**
	 * F​u​e​l​ ​C​a​p​a​c​i​t​y
	 */
	fuelCapacity: string
	/**
	 * F​u​e​l​ ​F​l​o​w
	 */
	fuelFlow: string
	/**
	 * F​u​e​l​ ​R​e​s​e​r​v​e
	 */
	fuelReserve: string
	/**
	 * I​n​c​l​u​d​e​ ​f​r​e​q​u​e​n​c​i​e​s
	 */
	includeFrequencies: string
	/**
	 * l​e​a​v​e​ ​a​ ​c​o​m​m​e​n​t
	 */
	leaveFeedback: string
	/**
	 * M​a​p
	 */
	map: string
	/**
	 * n​m
	 */
	nauticalMiles_unit: string
	/**
	 * N​o​t​e​s​…
	 */
	notes_placeholder: string
	/**
	 * o​p​e​n​ ​n​o​t​e​s
	 */
	openNotes: string
	/**
	 * P​l​a​n​e
	 */
	plane: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​f​l​i​g​h​t​ ​p​l​a​n
	 */
	removeFromPlan: string
	/**
	 * R​u​n​w​a​y​s
	 */
	runways: string
	/**
	 * S​e​a​r​c​h​ ​P​O​I​s
	 */
	searchPOI: string
	/**
	 * T​i​t​l​e
	 */
	title: string
	/**
	 * T​o​t​a​l​s
	 */
	totals: string
	/**
	 * W​i​n​d​ ​d​i​r​e​c​t​i​o​n​ ​a​n​d​ ​s​p​e​e​d​ ​[​d​i​r​/​s​p​e​e​d​]
	 */
	wind_help: string
	/**
	 * W​i​n​d
	 */
	wind: string
}

export type TranslationFunctions = {
	/**
	 * Add new
	 */
	addNew: () => LocalizedString
	/**
	 * Add to flight plan
	 */
	addToPlan: () => LocalizedString
	/**
	 * Airport
	 */
	airport: () => LocalizedString
	/**
	 * Altitude
	 */
	altitude: () => LocalizedString
	/**
	 * Call Sign
	 */
	callSign: () => LocalizedString
	cardinalDirections: {
		/**
		 * N
		 */
		N: () => LocalizedString
		/**
		 * E
		 */
		E: () => LocalizedString
		/**
		 * S
		 */
		S: () => LocalizedString
		/**
		 * W
		 */
		W: () => LocalizedString
	}
	/**
	 * check NOTAMs
	 */
	checkNOTAMs: () => LocalizedString
	/**
	 * close notes
	 */
	closeNotes: () => LocalizedString
	/**
	 * Coordinates
	 */
	coordinates: () => LocalizedString
	/**
	 * Course
	 */
	course: () => LocalizedString
	/**
	 * Cruise speed
	 */
	cruiseSpeed: () => LocalizedString
	/**
	 * Date
	 */
	date: () => LocalizedString
	/**
	 * Departure time
	 */
	departureTime: () => LocalizedString
	/**
	 * Dist.
	 */
	distance_abbr: () => LocalizedString
	/**
	 * Distance
	 */
	distance: () => LocalizedString
	dnd: {
		/**
		 * 
	      To pick up a draggable item, press the space bar.
	      While dragging, use the arrow keys to move the item.
	      Press space again to drop the item in its new position, or press escape to cancel.
	    
		 */
		draggable: () => LocalizedString
		/**
		 * Dragging was cancelled. Draggable item {active} was dropped.
		 */
		onDragCancel: (arg: { active: string }) => LocalizedString
		/**
		 * Draggable item {active} was dropped.
		 */
		onDragEnd: (arg: { active: string }) => LocalizedString
		/**
		 * Draggable item {active} was dropped over droppable area {over}.
		 */
		onDragEnd_over: (arg: { active: string, over: string }) => LocalizedString
		/**
		 * Draggable item {active} is no longer over a droppable area.
		 */
		onDragOver: (arg: { active: string }) => LocalizedString
		/**
		 * Draggable item {active} was moved over droppable area {over}.
		 */
		onDragOver_over: (arg: { active: string, over: string }) => LocalizedString
		/**
		 * Picked up draggable item {active}.
		 */
		onDragStart: (arg: { active: string }) => LocalizedString
	}
	/**
	 * drag leg
	 */
	dragLeg: () => LocalizedString
	/**
	 * Flight Plan
	 */
	flightPlan: () => LocalizedString
	/**
	 * Freq.
	 */
	frequencies_abbr: () => LocalizedString
	/**
	 * Frequencies
	 */
	frequencies: () => LocalizedString
	/**
	 * Fuel
	 */
	fuel: () => LocalizedString
	/**
	 * Fuel Capacity
	 */
	fuelCapacity: () => LocalizedString
	/**
	 * Fuel Flow
	 */
	fuelFlow: () => LocalizedString
	/**
	 * Fuel Reserve
	 */
	fuelReserve: () => LocalizedString
	/**
	 * Include frequencies
	 */
	includeFrequencies: () => LocalizedString
	/**
	 * leave a comment
	 */
	leaveFeedback: () => LocalizedString
	/**
	 * Map
	 */
	map: () => LocalizedString
	/**
	 * nm
	 */
	nauticalMiles_unit: () => LocalizedString
	/**
	 * Notes…
	 */
	notes_placeholder: () => LocalizedString
	/**
	 * open notes
	 */
	openNotes: () => LocalizedString
	/**
	 * Plane
	 */
	plane: () => LocalizedString
	/**
	 * Remove from flight plan
	 */
	removeFromPlan: () => LocalizedString
	/**
	 * Runways
	 */
	runways: () => LocalizedString
	/**
	 * Search POIs
	 */
	searchPOI: () => LocalizedString
	/**
	 * Title
	 */
	title: () => LocalizedString
	/**
	 * Totals
	 */
	totals: () => LocalizedString
	/**
	 * Wind direction and speed [dir/speed]
	 */
	wind_help: () => LocalizedString
	/**
	 * Wind
	 */
	wind: () => LocalizedString
}

export type Formatters = {}
